Table Walker {
    id int pk
    name varchar
}

Table City {
    id int pk
    name varchar
}

Table Dog {
    id int pk
    name varchar
    walkerId int [ref: > Walker.id]
}

Table WalkerCity {
    id int pk
    walkerId int [ref: > Walker.id]
    cityId int [ref: > City.id]
}